# Generated by Django 3.1.3 on 2022-11-18 12:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20221118_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 12, 12, 27, 170505, tzinfo=utc)),
        ),
    ]
